**Machine Learning Lab - CSE 432**

# 2 Data Exploration with pandas

**Pandas** is a software library written for the Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series. It is free software released under the three-clause BSD license.

In this lab, we will learn how to explore and manipulate data with the pandas library.

**2.1 Installing and Importing Pandas**

The following command is used to install pandas to your python system. If pandas is already installed, there is no need to run this command.

In [1]:
#!pip install pandas

In [2]:
import pandas as pd

**2.2 Importing a data set**

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
df = pd.read_csv('/content/drive/MyDrive/Machine learning lab/Data exploration /Week 2/titanic.csv')
print(df)

      pclass  survived                                             name  \
0        1.0       1.0                    Allen, Miss. Elisabeth Walton
1        1.0       1.0                   Allison, Master. Hudson Trevor
2        1.0       0.0                     Allison, Miss. Helen Loraine
3        1.0       0.0             Allison, Mr. Hudson Joshua Creighton
4        1.0       0.0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
...      ...       ...                                              ...
1305     3.0       0.0                            Zabour, Miss. Thamine
1306     3.0       0.0                        Zakarian, Mr. Mapriededer
1307     3.0       0.0                              Zakarian, Mr. Ortin
1308     3.0       0.0                               Zimmerman, Mr. Leo
1309     NaN       NaN                                              NaN

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000    0.0    0.0   24160  211.3375       B5        S    2
1       male   0.9167    1.0    2.0  113781  151.5500  C22 C26        S   11
2     female   2.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN
3       male  30.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN
4     female  25.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN
...      ...      ...    ...    ...     ...       ...      ...      ...  ...
1305  female      NaN    1.0    0.0    2665   14.4542      NaN        C  NaN
1306    male  26.5000    0.0    0.0    2656    7.2250      NaN        C  NaN
1307    male  27.0000    0.0    0.0    2670    7.2250      NaN        C  NaN
1308    male  29.0000    0.0    0.0  315082    7.8750      NaN        S  NaN
1309     NaN      NaN    NaN    NaN     NaN       NaN      NaN      NaN  NaN

       body                        home.dest
0       NaN                     St Louis, MO
1       NaN  Montreal, PQ / Chesterville, ON
2       NaN  Montreal, PQ / Chesterville, ON
3     135.0  Montreal, PQ / Chesterville, ON
4       NaN  Montreal, PQ / Chesterville, ON
...     ...                              ...
1305    NaN                              NaN
1306  304.0                              NaN
1307    NaN                              NaN
1308    NaN                              NaN
1309    NaN                              NaN

[1310 rows x 14 columns]

In [11]:
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
pd.set_option('display.max_rows', 10)
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
pd.set_option('display.max_rows', 20)
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**2.3 Viewing and Understanding Dataset**

In [20]:
df.head(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
5,1.0,1.0,"Anderson, Mr. Harry",male,48.0000,0.0,0.0,19952,26.5500,E12,S,3,NaN,"New York, NY"
6,1.0,1.0,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1.0,0.0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
7,1.0,0.0,"Andrews, Mr. Thomas Jr",male,39.0000,0.0,0.0,112050,0.0000,A36,S,NaN,NaN,"Belfast, NI"
8,1.0,1.0,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0000,2.0,0.0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"
9,1.0,0.0,"Artagaveytia, Mr. Ramon",male,71.0000,0.0,0.0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"

In [21]:
df.tail(5)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df.describe()

,pclass,survived,age,sibsp,parch,fare,body
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,121.000000
mean,2.294882,0.381971,29.881135,0.498854,0.385027,33.295479,160.809917
std,0.837836,0.486055,14.413500,1.041658,0.865560,51.758668,97.696922
min,1.000000,0.000000,0.166700,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,21.000000,0.000000,0.000000,7.895800,72.000000
50%,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200,155.000000
75%,3.000000,1.000000,39.000000,1.000000,0.000000,31.275000,256.000000
max,3.000000,1.000000,80.000000,8.000000,9.000000,512.329200,328.000000

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1310 entries, 0 to 1309
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   float64
 1   survived   1309 non-null   float64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   float64
 6   parch      1309 non-null   float64
 7   ticket     1309 non-null   object
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object
 10  embarked   1307 non-null   object
 11  boat       486 non-null    object
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object
dtypes: float64(7), object(7)
memory usage: 143.4+ KB

In [24]:
df.shape

(1310, 14)

In [25]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

In [26]:
df.isnull().sum()

pclass          1
survived        1
name            1
sex             1
age           264
sibsp           1
parch           1
ticket          1
fare            2
cabin        1015
embarked        3
boat          824
body         1189
home.dest     565
dtype: int64

In [27]:
df.nunique()

pclass          3
survived        2
name         1307
sex             2
age            98
sibsp           7
parch           8
ticket        929
fare          281
cabin         186
embarked        3
boat           27
body          121
home.dest     369
dtype: int64

**2.4 Slicing and Extracting Data**

In [31]:
# Isolating a single column
df['name'].head()

0                      Allen, Miss. Elisabeth Walton
1                     Allison, Master. Hudson Trevor
2                       Allison, Miss. Helen Loraine
3               Allison, Mr. Hudson Joshua Creighton
4    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
Name: name, dtype: object

In [33]:
# Isolating multiple columns
df[['name', 'sex', 'age']].head()

                                              name     sex      age
0                    Allen, Miss. Elisabeth Walton  female  29.0000
1                   Allison, Master. Hudson Trevor    male   0.9167
2                     Allison, Miss. Helen Loraine  female   2.0000
3             Allison, Mr. Hudson Joshua Creighton    male  30.0000
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000

In [35]:
# Isolating a single row
df.loc[0]

pclass                                 1.0
survived                               1.0
name         Allen, Miss. Elisabeth Walton
sex                                 female
age                                   29.0
sibsp                                  0.0
parch                                  0.0
ticket                               24160
fare                              211.3375
cabin                                   B5
embarked                                 S
boat                                     2
body                                   NaN
home.dest                     St Louis, MO
Name: 0, dtype: object

In [36]:
# Isolating multiple rows with range
df.loc[5:20]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
5,1.0,1.0,"Anderson, Mr. Harry",male,48.0,0.0,0.0,19952,26.5500,E12,S,3,NaN,"New York, NY"
6,1.0,1.0,"Andrews, Miss. Kornelia Theodosia",female,63.0,1.0,0.0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
7,1.0,0.0,"Andrews, Mr. Thomas Jr",male,39.0,0.0,0.0,112050,0.0000,A36,S,NaN,NaN,"Belfast, NI"
8,1.0,1.0,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2.0,0.0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"
9,1.0,0.0,"Artagaveytia, Mr. Ramon",male,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"
10,1.0,0.0,"Astor, Col. John Jacob",male,47.0,1.0,0.0,PC 17757,227.5250,C62 C64,C,NaN,124.0,"New York, NY"
11,1.0,1.0,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1.0,0.0,PC 17757,227.5250,C62 C64,C,4,NaN,"New York, NY"
12,1.0,1.0,"Aubart, Mme. Leontine Pauline",female,24.0,0.0,0.0,PC 17477,69.3000,B35,C,9,NaN,"Paris, France"
13,1.0,1.0,"Barber, Miss. Ellen ""Nellie""",female,26.0,0.0,0.0,19877,78.8500,NaN,S,6,NaN,NaN
14,1.0,1.0,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0.0,0.0,27042,30.0000,A23,S,B,NaN,"Hessle, Yorks"
15,1.0,0.0,"Baumann, Mr. John D",male,NaN,0.0,0.0,PC 17318,25.9250,NaN,S,NaN,NaN,"New York, NY"
16,1.0,0.0,"Baxter, Mr. Quigg Edmond",male,24.0,0.0,1.0,PC 17558,247.5208,B58 B60,C,NaN,NaN,"Montreal, PQ"
17,1.0,1.0,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0.0,1.0,PC 17558,247.5208,B58 B60,C,6,NaN,"Montreal, PQ"
18,1.0,1.0,"Bazzani, Miss. Albina",female,32.0,0.0,0.0,11813,76.2917,D15,C,8,NaN,NaN
19,1.0,0.0,"Beattie, Mr. Thomson",male,36.0,0.0,0.0,13050,75.2417,C6,C,A,NaN,"Winnipeg, MN"
20,1.0,1.0,"Beckwith, Mr. Richard Leonard",male,37.0,1.0,1.0,11751,52.5542,D35,S,5,NaN,"New York, NY"

In [37]:
# Isolating multiple rows with list
df.loc[[1, 5, 10, 6]]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
5,1.0,1.0,"Anderson, Mr. Harry",male,48.0000,0.0,0.0,19952,26.5500,E12,S,3,NaN,"New York, NY"
10,1.0,0.0,"Astor, Col. John Jacob",male,47.0000,1.0,0.0,PC 17757,227.5250,C62 C64,C,NaN,124.0,"New York, NY"
6,1.0,1.0,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1.0,0.0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"

In [38]:
dft = df.loc[5:20].copy()
dft.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
5,1.0,1.0,"Anderson, Mr. Harry",male,48.0,0.0,0.0,19952,26.5500,E12,S,3,NaN,"New York, NY"
6,1.0,1.0,"Andrews, Miss. Kornelia Theodosia",female,63.0,1.0,0.0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
7,1.0,0.0,"Andrews, Mr. Thomas Jr",male,39.0,0.0,0.0,112050,0.0000,A36,S,NaN,NaN,"Belfast, NI"
8,1.0,1.0,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2.0,0.0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"
9,1.0,0.0,"Artagaveytia, Mr. Ramon",male,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"

In [43]:
try:
    print(dft.loc[6])
except:
    print("There is an error")

pclass                                     1.0
survived                                   1.0
name         Andrews, Miss. Kornelia Theodosia
sex                                     female
age                                       63.0
sibsp                                      1.0
parch                                      0.0
ticket                                   13502
fare                                   77.9583
cabin                                       D7
embarked                                     S
boat                                        10
body                                       NaN
home.dest                           Hudson, NY
Name: 6, dtype: object

In [44]:
try:
    print(dft.iloc[0])
except:
    print("There is an error")

pclass                       1.0
survived                     1.0
name         Anderson, Mr. Harry
sex                         male
age                         48.0
sibsp                        0.0
parch                        0.0
ticket                     19952
fare                       26.55
cabin                        E12
embarked                       S
boat                           3
body                         NaN
home.dest           New York, NY
Name: 5, dtype: object

In [45]:
# Isolating both rows and columns with range
# loc[] doesn't work with column range but iloc[] does
df.iloc[0:20, 2:5].head()

                                              name     sex      age
0                    Allen, Miss. Elisabeth Walton  female  29.0000
1                   Allison, Master. Hudson Trevor    male   0.9167
2                     Allison, Miss. Helen Loraine  female   2.0000
3             Allison, Mr. Hudson Joshua Creighton    male  30.0000
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000

In [47]:
# Isolating both rows and columns with column names in list
# loc[] works but .iloc[] doesn't
df.loc[0:20, ['name', 'sex', 'age']].head()

                                              name     sex      age
0                    Allen, Miss. Elisabeth Walton  female  29.0000
1                   Allison, Master. Hudson Trevor    male   0.9167
2                     Allison, Miss. Helen Loraine  female   2.0000
3             Allison, Mr. Hudson Joshua Creighton    male  30.0000
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000

In [50]:
# That's how we change specific attribute of a single row
dft.loc[5, 'name'] = 'sakib'

# Change these attributes
dft.loc[5, 'sex'] = 'male'
dft.loc[5, 'age'] = 24
dft.loc[5, 'survived'] = 1
dft.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
5,1.0,1.0,sakib,male,24.0,0.0,0.0,19952,26.5500,E12,S,3,NaN,"New York, NY"
6,1.0,1.0,"Andrews, Miss. Kornelia Theodosia",female,63.0,1.0,0.0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
7,1.0,0.0,"Andrews, Mr. Thomas Jr",male,39.0,0.0,0.0,112050,0.0000,A36,S,NaN,NaN,"Belfast, NI"
8,1.0,1.0,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2.0,0.0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"
9,1.0,0.0,"Artagaveytia, Mr. Ramon",male,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"

In [51]:
# We can sort the data by an attribute
dft.sort_values(by='age', ascending=True).head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
11,1.0,1.0,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1.0,0.0,PC 17757,227.5250,C62 C64,C,4,NaN,"New York, NY"
5,1.0,1.0,sakib,male,24.0,0.0,0.0,19952,26.5500,E12,S,3,NaN,"New York, NY"
12,1.0,1.0,"Aubart, Mme. Leontine Pauline",female,24.0,0.0,0.0,PC 17477,69.3000,B35,C,9,NaN,"Paris, France"
16,1.0,0.0,"Baxter, Mr. Quigg Edmond",male,24.0,0.0,1.0,PC 17558,247.5208,B58 B60,C,NaN,NaN,"Montreal, PQ"
13,1.0,1.0,"Barber, Miss. Ellen ""Nellie""",female,26.0,0.0,0.0,19877,78.8500,NaN,S,6,NaN,NaN

**2.5 Slicing with Conditions**

Pandas slicing with conditions is a technique to select a subset of data from a pandas DataFrame or Series based on some criteria. For example, we can use the loc or iloc methods to slice by index labels or positions, and combine them with boolean masks to filter by values. Alternatively, we can use the query method to write the conditions as a string expression (which we will not use here).

In [52]:
# Let's find the underage people in the data set
df.loc[df['age']<18].head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.55,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.55,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
53,1.0,0.0,"Carrau, Mr. Jose Pedro",male,17.0000,0.0,0.0,113059,47.10,NaN,S,NaN,NaN,"Montevideo, Uruguay"
54,1.0,1.0,"Carter, Master. William Thornton II",male,11.0000,1.0,2.0,113760,120.00,B96 B98,S,4,NaN,"Bryn Mawr, PA"
55,1.0,1.0,"Carter, Miss. Lucile Polk",female,14.0000,1.0,2.0,113760,120.00,B96 B98,S,4,NaN,"Bryn Mawr, PA"

In [53]:
# Now let's find underage people who are also female
df.loc[ (df['age']<20) & (df['sex']=='female')].head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
11,1.0,1.0,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1.0,0.0,PC 17757,227.5250,C62 C64,C,4,NaN,"New York, NY"
27,1.0,1.0,"Bishop, Mrs. Dickinson H (Helen Walton)",female,19.0,1.0,0.0,11967,91.0792,B49,C,7,NaN,"Dowagiac, MI"
55,1.0,1.0,"Carter, Miss. Lucile Polk",female,14.0,1.0,2.0,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
92,1.0,1.0,"Dick, Mrs. Albert Adrian (Vera Gillespie)",female,17.0,1.0,0.0,17474,57.0000,B20,S,3,NaN,"Calgary, AB"

**2.6 Cleaning Data**

2.6.1 Dropping Missing Values

In [54]:
# We will copy the dataframe first in order to not change the original
dft = df.copy()
dft.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [55]:
dft.isnull().sum()

pclass          1
survived        1
name            1
sex             1
age           264
sibsp           1
parch           1
ticket          1
fare            2
cabin        1015
embarked        3
boat          824
body         1189
home.dest     565
dtype: int64

In [57]:
# Droppping missing values
dft = dft.dropna()
dft.head()

Empty DataFrame
Columns: [pclass, survived, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, boat, body, home.dest]
Index: []

In [58]:
dft = df.copy()
dft = dft.dropna(axis=1)
dft.head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

2.6.2 Replacing Missing Values

In [59]:
dft = df.copy()
dft.loc[dft['age'].isnull()].head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
15,1.0,0.0,"Baumann, Mr. John D",male,NaN,0.0,0.0,PC 17318,25.9250,NaN,S,NaN,NaN,"New York, NY"
37,1.0,1.0,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0.0,0.0,111427,26.5500,NaN,S,9,NaN,"Los Angeles, CA"
40,1.0,0.0,"Brewe, Dr. Arthur Jackson",male,NaN,0.0,0.0,112379,39.6000,NaN,C,NaN,NaN,"Philadelphia, PA"
46,1.0,0.0,"Cairns, Mr. Alexander",male,NaN,0.0,0.0,113798,31.0000,NaN,S,NaN,NaN,NaN
59,1.0,1.0,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,NaN,0.0,0.0,17770,27.7208,NaN,C,5,NaN,"New York, NY"

In [60]:
# Get the mean of age
mean_value = dft['age'].mean()
# Fill missing values using .fillna()
df5t = dft.fillna(mean_value)
dft.loc[dft['age'].isnull()].head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
15,1.0,0.0,"Baumann, Mr. John D",male,NaN,0.0,0.0,PC 17318,25.9250,NaN,S,NaN,NaN,"New York, NY"
37,1.0,1.0,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0.0,0.0,111427,26.5500,NaN,S,9,NaN,"Los Angeles, CA"
40,1.0,0.0,"Brewe, Dr. Arthur Jackson",male,NaN,0.0,0.0,112379,39.6000,NaN,C,NaN,NaN,"Philadelphia, PA"
46,1.0,0.0,"Cairns, Mr. Alexander",male,NaN,0.0,0.0,113798,31.0000,NaN,S,NaN,NaN,NaN
59,1.0,1.0,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,NaN,0.0,0.0,17770,27.7208,NaN,C,5,NaN,"New York, NY"

In [61]:
df5t.loc[dft['age'].isnull()].head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
15,1.0,0.0,"Baumann, Mr. John D",male,29.881135,0.0,0.0,PC 17318,25.9250,29.881135,S,29.881135,29.881135,"New York, NY"
37,1.0,1.0,"Bradley, Mr. George (""George Arthur Brayton"")",male,29.881135,0.0,0.0,111427,26.5500,29.881135,S,9,29.881135,"Los Angeles, CA"
40,1.0,0.0,"Brewe, Dr. Arthur Jackson",male,29.881135,0.0,0.0,112379,39.6000,29.881135,C,29.881135,29.881135,"Philadelphia, PA"
46,1.0,0.0,"Cairns, Mr. Alexander",male,29.881135,0.0,0.0,113798,31.0000,29.881135,S,29.881135,29.881135,29.881135
59,1.0,1.0,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,29.881135,0.0,0.0,17770,27.7208,29.881135,C,5,29.881135,"New York, NY"

2.6.3 Removing Duplicates

In [62]:
dft = df.copy()
dft.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [63]:
dft = dft.drop_duplicates()
dft.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

**2.7 Manipulating Columns**

In [ ]:
# We can rename a column using the rename() method
dft = dft.rename(columns = {'home.dest':'destination'})
dft.head()

In [ ]:
# Now we will add a new column named baby
# baby is a boolean value column (1 or 0)
# It will show whether a passenger was a baby or not
dft['baby'] = 1
dft.loc[dft['age']>10, 'baby'] = 0
dft.head()

**2.8 Further Analysis**

In [ ]:
# We can find mean, median, mode
df['age'].mean()

In [ ]:
# Find mean of age of females and males individually
df.groupby('sex')['age'].mean()